[tools]
rust = "nightly"

[tasks."run:benchmarks-rust"]
outputs=["rust_peko_s3ue02/out/results.json"]
sources=["rust_peko_s3ue02/src/**"]
dir="rust_peko_s3ue02/"
description = "Run the benchmarks for the Rust implementation"
run = "cargo run --release"

[tasks."build:documenation"]
depends = ["run:benchmarks-rust"]
description="Build the typst documentation"
run = [
    "cp rust_peko_s3ue02/out/results.json assets/benchmarks_results.json",
    "typst compile SWE3_Peko_UE02.typ"
]
